# Site wide configuration

title:            Sumedh Joshi
locale:           en_US
url:              http://www.sumedhjoshi.com
#url:              localhost:4000

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Sumedh Joshi
  avatar: bio-photo.jpg
  bio: "PhD Candidate, Applied Math"
  email: sumedh.m.joshi@gmail.com
  disqus-shortname: sumedhjoshi
  twitter: SumedhJoshiUT
  facebook: sumedh.joshi.12
  google:
    plus:
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: sumedhjoshi
  stackoverflow: #http://scicomp.stackexchange.com/users/4879/sumedh-joshi
  linkedin: sumedhjoshi
  xing: #username
  instagram: phdmyselfandi
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
