# Site wide configuration

title:            Sumedh Joshi
locale:           en_US
url:              https://www.sumedhmjoshi.com
#url:             localhost:4000
description:      Personal Site of the late Sumedh Joshi, computational physicist, football nerd, obsessive musician, and loved and missed every day.
respository:      aledlie/Homage
og_image:         /images/default-thumb.png
analytics:
  provider: "google-gtag" # Or "google-universal" if using an older UA ID
  google:
    tracking_id: G-WGG5H639B7
    anonymize_ip: false # Optional, default is false

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: false
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

plugins:
  - jekyll-coffeescript

# Site owner
owner:
  name: Sumedh Joshi
  avatar: bio-photo.jpg
  bio: "Applied Mathematician"
  email: sumedh.m.joshi@gmail.com
  disqus-shortname: sumedhjoshi
  twitter: SumedhJoshiUT
  facebook: sumedh.joshi.12
  google:
    plus:
    analytics: G-WGG5H639B7
    verify: gqKcgBHjbuRW6cYY8BO_GdFOVNsIekipkuiC_2pb6g0
    ad-client:
    ad-slot:
  bing-verify:
  github: sumedhjoshi
  stackoverflow:
  scicomp.stackexchange: scicomp.stackexchange
  linkedin: sumedhjoshi
  xing: https://x.com/SumedhJoshiUT
  instagram: phdmyselfandi
  goodreads: https://www.goodreads.com/user/show/25170232-sumedh-joshi
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
